In [3]:
import numpy as np

In [4]:
array = np.random.randint(0,10,10)
array

array([7, 9, 2, 1, 6, 5, 9, 3, 9, 7], dtype=int32)

In [5]:
array.shape

(10,)

In [10]:
# we can reshape the array and it the multiplication of the two numbers have to be the number of array which was predefined.
array.reshape(5,2)

array([[7, 9],
       [2, 1],
       [6, 5],
       [9, 3],
       [9, 7]], dtype=int32)

In [51]:
data = np.random.randint(0,10,(3,3))
data

array([[7, 4, 5],
       [8, 3, 7],
       [0, 9, 0]], dtype=int32)

In [52]:
# this function is used to flatened the multidimentional array
y= data.ravel() ## it will not create deep copy and we can do modification on the array
y

array([7, 4, 5, 8, 3, 7, 0, 9, 0], dtype=int32)

In [53]:
# lIKe
y[0] = 200  ## it will modify the the value of 0 index 
y

array([200,   4,   5,   8,   3,   7,   0,   9,   0], dtype=int32)

In [54]:
data #it will cmodify the vaue of original array also

array([[200,   4,   5],
       [  8,   3,   7],
       [  0,   9,   0]], dtype=int32)

In [44]:
data1 = np.random.randint(0,10,(3,3))
data1

array([[1, 7, 3],
       [7, 3, 7],
       [3, 0, 5]], dtype=int32)

In [45]:
x= data1.flatten() # It will create the shallow copy and will not modify the original array
x

array([1, 7, 3, 7, 3, 7, 3, 0, 5], dtype=int32)

In [46]:
## like
x[0] = 200
x

array([200,   7,   3,   7,   3,   7,   3,   0,   5], dtype=int32)

In [47]:
data1  ## here it will not changre the valye of 0 index in the array

array([[1, 7, 3],
       [7, 3, 7],
       [3, 0, 5]], dtype=int32)

In [56]:
data1.T ## it is transpose of the data it actually converts the column to rows and rows to column

array([[1, 7, 3],
       [7, 3, 0],
       [3, 7, 5]], dtype=int32)

In [59]:
data

array([[200,   4,   5],
       [  8,   3,   7],
       [  0,   9,   0]], dtype=int32)

In [60]:
data1

array([[1, 7, 3],
       [7, 3, 7],
       [3, 0, 5]], dtype=int32)

In [63]:
## concatenation

np.concatenate((data,data1),axis = 0) # row level concatenation

array([[200,   4,   5],
       [  8,   3,   7],
       [  0,   9,   0],
       [  1,   7,   3],
       [  7,   3,   7],
       [  3,   0,   5]], dtype=int32)

In [64]:
np.concatenate((data,data1),axis = 1) # column level concatenation

array([[200,   4,   5,   1,   7,   3],
       [  8,   3,   7,   7,   3,   7],
       [  0,   9,   0,   3,   0,   5]], dtype=int32)

In [65]:
# suppose

a = np.random.randint(0,10,(3,3))
a

array([[1, 6, 8],
       [9, 4, 7],
       [2, 7, 0]], dtype=int32)

In [67]:
b = np.random.randint(0,10,(3,2))
b

array([[8, 8],
       [4, 8],
       [6, 5]], dtype=int32)

In [72]:
# now lets do the concatenation 
np.concatenate((a,b), axis=0 )
# it will not perform thr operation because the coloumn size is different

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [73]:
np.concatenate((a,b), axis=1 ) 
# it will perform the operation because the coloumn size is same

array([[1, 6, 8, 8, 8],
       [9, 4, 7, 4, 8],
       [2, 7, 0, 6, 5]], dtype=int32)

In [78]:
np.vstack((a,b)) # Here also it will not perform because the size is different

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [79]:
np.hstack((a,b)) # Here it will perform because the coloumn size is same

array([[1, 6, 8, 8, 8],
       [9, 4, 7, 4, 8],
       [2, 7, 0, 6, 5]], dtype=int32)

In [82]:
data2 = np.random.randint(0,10,(4,4))
data2

array([[2, 5, 8, 7],
       [5, 0, 6, 6],
       [4, 9, 1, 9],
       [7, 2, 2, 1]], dtype=int32)

In [91]:
np.split(data2,2,axis=1)

[array([[2, 5],
        [5, 0],
        [4, 9],
        [7, 2]], dtype=int32),
 array([[8, 7],
        [6, 6],
        [1, 9],
        [2, 1]], dtype=int32)]

In [93]:
np.split(data2,4,axis=0)

[array([[2, 5, 8, 7]], dtype=int32),
 array([[5, 0, 6, 6]], dtype=int32),
 array([[4, 9, 1, 9]], dtype=int32),
 array([[7, 2, 2, 1]], dtype=int32)]

In [94]:
np.hsplit(data2,2)

[array([[2, 5],
        [5, 0],
        [4, 9],
        [7, 2]], dtype=int32),
 array([[8, 7],
        [6, 6],
        [1, 9],
        [2, 1]], dtype=int32)]

In [95]:
np.vsplit(data2,2)

[array([[2, 5, 8, 7],
        [5, 0, 6, 6]], dtype=int32),
 array([[4, 9, 1, 9],
        [7, 2, 2, 1]], dtype=int32)]

In [ ]:
### SET functions in NUMPY

In [4]:
g = np.array([1,2,3,4,9,3,4,6,7])
g

array([1, 2, 3, 4, 9, 3, 4, 6, 7])

In [5]:
h = np.array([4,5,6,7]) 
h

array([4, 5, 6, 7])

In [7]:
np.unique(g)

array([1, 2, 3, 4, 6, 7, 9])

In [8]:
np.intersect1d(g,h)

array([4, 6, 7])

In [9]:
np.setdiff1d(g,h)

array([1, 2, 3, 9])

In [10]:
np.setdiff1d(h,g)

array([5])

In [ ]:
####

In [11]:
sales= np.random.randint(10,100,10)
sales

array([89, 19, 76, 41, 12, 11, 42, 26, 66, 96], dtype=int32)

In [12]:
# how many customer bought above 50
sales[sales>50].shape

(4,)

In [14]:
len(sales[sales>50]) # it will also give the same result

4

In [18]:
# how many of the customers bought above the average value
len(sales[sales>=sales.mean()])

4

In [19]:
sales[sales>=sales.mean()]

array([89, 76, 66, 96], dtype=int32)

In [20]:
# how many of the customers bought below the average value
len(sales[sales<=sales.mean()])

6

In [21]:
sales[sales<=sales.mean()]

array([19, 41, 12, 11, 42, 26], dtype=int32)

In [5]:
## asuming 10 stores and 5 products with those sales value
sales = np.random.randint(1,100,(10,5))
sales

array([[76, 75, 47, 11, 10],
       [73, 63, 75, 38, 41],
       [99, 27, 48, 76, 52],
       [64, 67, 44, 93, 44],
       [39, 41, 36, 92, 67],
       [22, 31, 13, 14, 77],
       [41, 78, 64, 47, 26],
       [57, 25, 98,  9, 41],
       [89, 15,  6, 41, 15],
       [96, 12, 17, 33,  7]], dtype=int32)

In [6]:
## saggregating store 1
sales[0,]

array([76, 75, 47, 11, 10], dtype=int32)

In [7]:
## what is the total sales done by store 1
sales[0,].sum()

np.int64(219)

In [8]:
# total sales of each store
sales.sum(axis=1)

array([219, 290, 302, 312, 275, 157, 256, 230, 166, 165])

In [9]:
# max sales of produts store wise
sales.max(axis=1)

array([76, 75, 99, 93, 92, 77, 78, 98, 89, 96], dtype=int32)

In [10]:
max(sales.max(axis=1))

np.int32(99)

In [11]:
# in which store it has the maximum sales for product 1

sales[:,0].argmax()+1   # here we have put +1 because the index starts from 0 but to get the exact number we need to do so

np.int64(3)

In [12]:
sales

array([[76, 75, 47, 11, 10],
       [73, 63, 75, 38, 41],
       [99, 27, 48, 76, 52],
       [64, 67, 44, 93, 44],
       [39, 41, 36, 92, 67],
       [22, 31, 13, 14, 77],
       [41, 78, 64, 47, 26],
       [57, 25, 98,  9, 41],
       [89, 15,  6, 41, 15],
       [96, 12, 17, 33,  7]], dtype=int32)

In [19]:
## which product on an average is making more sales
sales.mean(axis=0).argmax()+1

np.int64(1)

In [20]:
sales.mean(axis=0)

array([65.6, 43.4, 44.8, 45.4, 38. ])

In [24]:
sales

array([[76, 75, 47, 11, 10],
       [73, 63, 75, 38, 41],
       [99, 27, 48, 76, 52],
       [64, 67, 44, 93, 44],
       [39, 41, 36, 92, 67],
       [22, 31, 13, 14, 77],
       [41, 78, 64, 47, 26],
       [57, 25, 98,  9, 41],
       [89, 15,  6, 41, 15],
       [96, 12, 17, 33,  7]], dtype=int32)

| Store     | Sales | units     | txn       |customer   | profit    | drive through
|-----------|-------|-----------|-----------|-----------|-----------|

| Store 1   | 76    | 75        | 47        | 11        | 10        | 0
| Store 2   | 73    | 63        | 75        | 38        | 41        | 1
| Store 3   | 99    | 27        | 48        | 76        | 52        | 0
| Store 4   | 64    | 67        | 44        | 93        | 44        | 1
| Store 5   | 39    | 41        | 36        | 92        | 67        | 0
| Store 6   | 22    | 31        | 13        | 14        | 77        | 0
| Store 7   | 41    | 78        | 64        | 47        | 26        | 1
| Store 8   | 57    | 25        | 98        |  9        | 41        | 0
| Store 9   | 89    | 15        |  6        | 41        | 15        | 1
| Store 10  | 96    | 12        | 17        | 33        |  7        | 0

In [37]:
## which store has the max basket value BASKET VALUE= (SALES/TXN)
(sales[:,0]/sales[:,2])

array([ 1.61702128,  0.97333333,  2.0625    ,  1.45454545,  1.08333333,
        1.69230769,  0.640625  ,  0.58163265, 14.83333333,  5.64705882])

In [41]:
# to convert the float to integer we need to use ASTYPE(INT) function
(sales[:,0]/sales[:,2]).astype(int)

array([ 1,  0,  2,  1,  1,  1,  0,  0, 14,  5])

In [42]:
(sales[:,0]/sales[:,2]).argmax()+1

np.int64(9)

In [44]:
import numpy as np

data = np.array([[76, 75, 47, 11, 10, 0],
       [73, 63, 75, 38, 41, 1],
       [99, 27, 48, 76, 52, 0],
       [64, 67, 44, 93, 44, 1],
       [39, 41, 36, 92, 67, 0],
       [22, 31, 13, 14, 77, 0],
       [41, 78, 64, 47, 26, 1],
       [57, 25, 98,  9, 41, 0],
       [89, 15,  6, 41, 15, 1],
       [96, 12, 17, 33,  7, 0]])
print (data)


[[76 75 47 11 10  0]
 [73 63 75 38 41  1]
 [99 27 48 76 52  0]
 [64 67 44 93 44  1]
 [39 41 36 92 67  0]
 [22 31 13 14 77  0]
 [41 78 64 47 26  1]
 [57 25 98  9 41  0]
 [89 15  6 41 15  1]
 [96 12 17 33  7  0]]


In [45]:
data

array([[76, 75, 47, 11, 10,  0],
       [73, 63, 75, 38, 41,  1],
       [99, 27, 48, 76, 52,  0],
       [64, 67, 44, 93, 44,  1],
       [39, 41, 36, 92, 67,  0],
       [22, 31, 13, 14, 77,  0],
       [41, 78, 64, 47, 26,  1],
       [57, 25, 98,  9, 41,  0],
       [89, 15,  6, 41, 15,  1],
       [96, 12, 17, 33,  7,  0]])

In [47]:
## find if the drive through store are giving more sales or not

if data[data[:,-1]==0].sum()>data[data[:,-1]==1].sum():
    print ("no drive through store")
else:
    ("drive through")

no drive through store


In [2]:
import numpy as np

In [ ]:
## broadcasting

In [ ]:
## ROW LEVEL BROADCASTING

In [5]:
x = np.random.randint(0,10,(3,3))
x

array([[0, 9, 7],
       [7, 5, 8],
       [5, 4, 3]], dtype=int32)

In [7]:
y = 10

In [9]:
x+y ## here the value of y(10) will be added to each of the element of x

array([[10, 19, 17],
       [17, 15, 18],
       [15, 14, 13]], dtype=int32)

In [10]:
y = np.random.randint(0,10,(1,3))
y

array([[3, 7, 3]], dtype=int32)

In [16]:
x+y  ## here the element of y will be added to elementd of x at row level

array([[ 9, 18, 16],
       [ 7,  5,  8],
       [14, 13, 12]], dtype=int32)

In [ ]:
## COLOUMN LEVEL BROADCASTING

In [15]:
x

array([[0, 9, 7],
       [7, 5, 8],
       [5, 4, 3]], dtype=int32)

In [13]:
y = np.random.randint(0,10,(3,1))
y

array([[9],
       [0],
       [9]], dtype=int32)

In [17]:
x+y ## here the element of y will be added to elementd of x at coloumn level

array([[ 9, 18, 16],
       [ 7,  5,  8],
       [14, 13, 12]], dtype=int32)

In [18]:
x = np.random.randint(0,10,(1,3))
x

array([[4, 9, 9]], dtype=int32)

In [19]:
y = np.random.randint(0,10,(3,1))
y

array([[7],
       [9],
       [8]], dtype=int32)

In [21]:
x+y ## here all the row level elements are getting added to the coloumn level elements to extend the array

array([[11, 16, 16],
       [13, 18, 18],
       [12, 17, 17]], dtype=int32)

In [25]:
import cv2
data = cv2.imread(r"C:\Users\dell\Desktop\DE CLASSES PYTHON\Python codes\Screenshot 2025-06-16 052801.png")

ModuleNotFoundError: No module named 'cv2'