In [4]:
### NUMPY

In [ ]:
## Import numpy as np

In [2]:
import numpy as np  # Import NumPy
x = [1, 2, 3, 4, 5]  # Example list
y = np.array(x)      # Convert list to array
print(y)

[1 2 3 4 5]


In [31]:
type(y)

numpy.ndarray

In [7]:
x = ["data","science",2.61,3,4]
y = np.array(x)

In [8]:
y

array(['data', 'science', '2.61', '3', '4'], dtype='<U32')

In [10]:
type(x)

list

In [11]:
type(y)

numpy.ndarray

In [23]:
x= [[1,2],[3,4]]

In [27]:
y=np.array(x)

In [28]:
y

array([[1, 2],
       [3, 4]])

In [29]:
type(y)

numpy.ndarray

In [38]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [39]:

np.info(x)

class:  ndarray
shape:  (4,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x1e5233944b0
byteorder:  little
byteswap:  False
type: int64


In [43]:
y = np.array([[1,2],[3,4]])
y

array([[1, 2],
       [3, 4]])

In [42]:
np.info(y)

class:  ndarray
shape:  (2, 2)
strides:  (16, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x1e523394540
byteorder:  little
byteswap:  False
type: int64


In [45]:
x.dtype, y.dtype

(dtype('int64'), dtype('int64'))

In [46]:
len(x), len(y)

(4, 2)

In [48]:
x.ndim ,y.ndim

(1, 2)

In [49]:
x.itemsize, y.itemsize

(8, 8)

In [ ]:
### DATA CREATION FUNCTION

In [58]:
# forward order (incremental)
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [57]:
# reverse order (decremental)

np.arange(10,0,-2)

array([10,  8,  6,  4,  2])

In [59]:
# to generate a random number between 0-10

np.random.randint(0,10)

5

In [60]:
# to generate 5 random number between 0-10

np.random.randint(0,10,5)

array([9, 0, 4, 9, 9], dtype=int32)

In [62]:
# to generate an multidimensional array
#(3,2) is refering (3 rows, 2 coloumns)

np.random.randint(0,10,(3,2))

array([[6, 6],
       [2, 1],
       [2, 2]], dtype=int32)

In [63]:
# to generate random numbers between (0-1) which will be in decimal

np.random.rand(5)

array([0.04643353, 0.58853069, 0.6700938 , 0.99496404, 0.36360843])

In [64]:
# normal distribution of data (where its refer to the average of 0,where some numbers are positive and some are negetive)

np.random.randn(10)

array([ 0.61340444,  1.35951449,  0.33108946, -1.06287225, -0.49467615,
        0.76555505,  1.00418261, -1.87208541,  1.39971897, -1.18022569])

In [65]:
# mean() refers to the close number to 0 (MEAN)

np.random.randn(10).mean()

np.float64(-0.231622681796707)

In [66]:
# std() refers to the close number to 1 (standard deviation)

np.random.randn(10).std()

np.float64(0.7839704958863493)

In [5]:
x = np.random.randint(0,10,(5,5))
x

array([[1, 6, 3, 1, 2],
       [5, 6, 1, 7, 9],
       [8, 9, 3, 6, 6],
       [6, 8, 7, 0, 2],
       [1, 5, 6, 1, 6]], dtype=int32)

In [11]:
x[0,0]

np.int32(5)

In [12]:
x[0:2,0]

array([5, 1], dtype=int32)

In [13]:
x[0:2,0:2]

array([[5, 3],
       [1, 1]], dtype=int32)

In [6]:
x[2:5,3:5]

array([[6, 6],
       [0, 2],
       [1, 6]], dtype=int32)

In [16]:
x

array([[5, 3, 4, 4, 2],
       [1, 1, 4, 8, 7],
       [2, 6, 6, 2, 6],
       [6, 3, 3, 0, 8],
       [2, 2, 2, 1, 5]], dtype=int32)

In [15]:
x[-2:-1,-2:-1] 

array([[0]], dtype=int32)

In [7]:
x[-3:-1,-2:]

array([[6, 6],
       [0, 2]], dtype=int32)

In [ ]:
### INBUILT functions in NUMPY Array

In [10]:
x = np.random.randint(0,10,(2,2))
y = np.random.randint(0,10,(2,2)) 

In [12]:
x

array([[1, 0],
       [2, 2]], dtype=int32)

In [13]:
y

array([[4, 4],
       [0, 0]], dtype=int32)

In [14]:
np.add(x,y)

array([[5, 4],
       [2, 2]], dtype=int32)

In [15]:
np.multiply(x,y)

array([[4, 0],
       [0, 0]], dtype=int32)

In [16]:
np.subtract(x,y)

array([[-3, -4],
       [ 2,  2]], dtype=int32)

In [19]:
np.divide(x,y)

C:\Users\dell\AppData\Local\Temp\ipykernel_11176\430945158.py:1: RuntimeWarning: divide by zero encountered in divide
  np.divide(x,y)


array([[0.25, 0.  ],
       [ inf,  inf]])

In [20]:
np.floor_divide(x,y)

C:\Users\dell\AppData\Local\Temp\ipykernel_11176\2566742545.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.floor_divide(x,y)


array([[0, 0],
       [0, 0]], dtype=int32)

In [21]:
np.mod(x,y)

C:\Users\dell\AppData\Local\Temp\ipykernel_11176\965914413.py:1: RuntimeWarning: divide by zero encountered in remainder
  np.mod(x,y)


array([[1, 0],
       [0, 0]], dtype=int32)

In [22]:
np.power(x,y)

array([[1, 0],
       [1, 1]], dtype=int32)

In [23]:
x,y

(array([[1, 0],
        [2, 2]], dtype=int32),
 array([[4, 4],
        [0, 0]], dtype=int32))

In [24]:
np.add(x,10)

array([[11, 10],
       [12, 12]], dtype=int32)

In [ ]:
### FORMATTING FUNCTION

In [26]:
y=x/3
y

array([[0.33333333, 0.        ],
       [0.66666667, 0.66666667]])

In [27]:
np.round(y)

array([[0., 0.],
       [1., 1.]])

In [31]:
y= np.array([[1.6,2.3],[3.4,3.9]])
y

array([[1.6, 2.3],
       [3.4, 3.9]])

In [32]:
np.round(y)

array([[2., 2.],
       [3., 4.]])

In [33]:
y= np.array([[-1.6,-2.3],[-3.4,-3.9]])
y

array([[-1.6, -2.3],
       [-3.4, -3.9]])

In [34]:
np.round(y)

array([[-2., -2.],
       [-3., -4.]])

In [35]:
np.ceil(y)

array([[-1., -2.],
       [-3., -3.]])

In [36]:
np.fix(y)

array([[-1., -2.],
       [-3., -3.]])

In [ ]:
### LOG and EXPONENTIAL

In [37]:
import math
math.e

2.718281828459045

In [38]:
math.pi

3.141592653589793

In [39]:
math.tau

6.283185307179586

In [40]:
np.exp(2)

np.float64(7.38905609893065)

In [41]:
np.power(2.718281828459045,-2)

np.float64(0.1353352832366127)

In [43]:
# expm1 stand for exponential minus one(exp-1)
np.expm1(2)

np.float64(6.38905609893065)

In [44]:
np.log(math.e)

np.float64(1.0)

In [45]:
np.log2(2)

np.float64(1.0)

In [46]:
np.log2(16)

np.float64(4.0)

In [ ]:
### STATISTICAL FUNCTIONS

In [14]:
# mean

data=np.array([1,2,3,4,56,7,100])
np.mean(data)

np.float64(24.714285714285715)

In [15]:
# median

np.median(data)

np.float64(4.0)

In [17]:
# mode
# mode is not available in NUMPY


In [18]:
# standard deviation formula √(Σ(xᵢ - μ)² / N)

np.sqrt(sum((data-data.mean())**2)/7)

np.float64(35.73599340286759)

In [19]:
np.std(data)

np.float64(35.73599340286759)

In [20]:
# VARIANCE
np.var(data)

np.float64(1277.061224489796)

In [ ]:
# QUANTILE

In [24]:
np.quantile(data,0.25)

np.float64(2.5)

In [25]:
np.quantile(data,0.50)

np.float64(4.0)

In [26]:
# MINIMUM

np.min(data)

np.int64(1)

In [27]:
# MAXIMUM

np.max(data)

np.int64(100)

In [28]:
# trigonomatric functions

np.sin(x)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [29]:
np.tan(x)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [32]:
# prod is nothing but multiplications
np.prod(x)

np.int64(120)

In [34]:
z= np.random.randint(0,10,(3,3))
z

array([[4, 2, 5],
       [0, 3, 2],
       [5, 0, 3]], dtype=int32)

In [35]:
z.sum()

np.int64(24)

In [38]:
z.sum(axis=1)

array([11,  5,  8])

In [39]:
z.sum(axis=0)

array([ 9,  5, 10])

In [49]:
w= np.random.randint(0,2,(4,4))
w

array([[1, 1, 1, 1],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 1, 1]], dtype=int32)

In [50]:
w.sum(axis=1)

array([4, 1, 1, 3])

In [51]:
w.mean()

np.float64(0.5625)

In [52]:
w.mean(axis=1)

array([1.  , 0.25, 0.25, 0.75])

In [53]:
w.mean(axis=0)

array([0.5 , 0.5 , 0.75, 0.5 ])

In [58]:
x

array([[6, 7, 5],
       [2, 0, 6],
       [3, 3, 8]], dtype=int32)

In [59]:
x.min(axis=1)

array([5, 0, 3], dtype=int32)

In [61]:
x.max(axis=0)

array([6, 7, 8], dtype=int32)

In [62]:
x.argmax(axis=0)

array([0, 0, 2])

In [63]:
x.argmin(axis=0)

array([1, 1, 0])

In [4]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.ones([10,10])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [6]:
# IDENTITY MATRIX

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
# TO GET THE LINEAR VALUE (the difference between fourth and 2nd is eual to the difference between 1st and 3rd)

np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [11]:
data = np.random.randint(0,100,10)
data

array([83, 24, 68,  3, 97, 63, 35, 63, 75, 53], dtype=int32)

In [12]:
data>50

array([ True, False,  True, False,  True,  True, False,  True,  True,
        True])

In [13]:
data[data>50]

array([83, 68, 97, 63, 63, 75, 53], dtype=int32)

In [15]:
# LEVEL ENCODING

np.where(data>50,"high","low")

array(['high', 'low', 'high', 'low', 'high', 'high', 'low', 'high',
       'high', 'high'], dtype='<U4')

In [16]:
# any of the output is true that is why it is returning as true
np.any(data>50)

np.True_

In [17]:
# because not all the poutputs are true so its is resulting false
np.all(data>50)

np.False_